export default [
{perms: "config-add", view: () => import('@/sa-view/config/add.vue')},
{perms: "user-add", view: () => import('@/sa-view/user/add.vue')},
{perms: "user-list", view: () => import('@/sa-view/user/list.vue')},
{perms: "permission-list", view: () => import('@/sa-view/permission/list.vue')},
{perms: "file-add", view: () => import('@/sa-view/file/add.vue')},
{perms: "article-list", view: () => import('@/sa-view/article/list.vue')},
{perms: "role-add", view: () => import('@/sa-view/role/add.vue')},
{perms: "sys-config", view: () => import('@/sa-view/cfg/system-cfg.vue')},
{perms: "file-list", view: () => import('@/sa-view/file/file-list.vue')},
{perms: "file-list", view: () => import('@/sa-view/file/list.vue')},
{perms: "article-add", view: () => import('@/sa-view/article/add.vue')},
{perms: "log-add", view: () => import('@/sa-view/log/add.vue')},
{perms: "permission-add", view: () => import('@/sa-view/permission/add.vue')},
{perms: "role-list", view: () => import('@/sa-view/role/role-list.vue')},
{perms: "log-list", view: () => import('@/sa-view/log/list.vue')},
];